const koa = require('./src/koa')
const { router, register, methods } = require('./src/common')
const login = require('./src/login')
const circle = require('./src/circle')
const resource = require('./src/resource')
const schedule = require('./src/schedule')
const ingetral = require('./src/ingetral')
const voucher = require('./src/voucher')

register('/login', [methods.POST], login.login, { ignoreLogin: true })
register('/get_auth_code', [methods.POST], login.get_auth_code, { ignoreLogin: true })
register('/get_phone_umber', [methods.POST], login.get_phone_umber)
register('/bind_phone', [methods.POST], login.bind_phone)
register('/circle', [methods.POST, methods.PUT, methods.DELETE, methods.GET], circle.circle)
register('/circle_join', [methods.POST], circle.circle_join)
register('/circle_quit', [methods.POST], circle.circle_quit)
register('/circle_List', [methods.GET], circle.circle_list)
register('/circle_voucher_edit', [methods.POST], circle.circle_voucher_edit)
register('/circle_notice_edit', [methods.POST], circle.circle_notice_edit)
register('/resource', [methods.POST, methods.PUT, methods.DELETE, methods.GET], resource.resource)
register('/resource_list', [methods.POST], resource.resource_list)
register('/resource_list_with_myself', [methods.GET], resource.resource_list_with_myself)
register('/list_with_user_collect', [methods.GET], resource.list_with_user_collect)
register('/circle_with_user_join', [methods.GET], resource.circle_with_user_join)
register('/resource_collect', [methods.POST], resource.resource_collect)
register('/resource_recommended', [methods.POST], resource.resource_recommended)
register('/resource_recommended_refund', [methods.POST], resource.resource_recommended_refund)
register('/add_ingetral', [methods.POST], ingetral.add_ingetral)
register('/upload_img', [methods.POST], resource.upload_img)
register('/get_user_voucher_count', [methods.GET], login.get_user_voucher_count)
register('/voucher_trad_action', [methods.POST], voucher.voucher_trad_action)
register('/get_user_voucher', [methods.POST], voucher.get_user_voucher)
register('/get_user_info', [methods.POST], login.get_user_info)


koa.router.use(router.routes(), router.allowedMethods())

koa.enableRouter()


schedule.myEmitter.emit('start_schedule')
